apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: glusterfs
      labels:
        app: {{ template "fullname" . }}
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: glusterfs-simple-provisioner
    spec:
      serviceAccountName: {{ template "fullname" . }}
      containers:
        - image: "{{ .Values.provisioner.image.repository }}:{{ .Values.provisioner.image.tag }}"
          imagePullPolicy: {{ .Values.provisioner.image.pullPolicy }}
          name: glusterfs-simple-provisioner
          command:
          - /glusterfs-simple-provisioner
          - -v={{ .Values.log.level }}
